version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  phlosales.auth:
    image: ${DOCKER_REGISTRY-}phlosalesauth
    build:
      context: .
      dockerfile: src/PhloSales.Auth/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy 
    environment:
        - CONNECTION_STRING=Server=tcp:sqlserver,1433;Database=phloauth;User Id=sa;Password=Pass@word;Integrated Security=false;TrustServerCertificate=true
        - BEARER_KEY=8833933cf99240db9389db678345b119
    ports:
      - 5001:80

  phlosales.server:
    image: ${DOCKER_REGISTRY-}phlosalesserver
    build:
      context: .
      dockerfile: src/PhloSales.Server/Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
        - CONNECTION_STRING=Server=tcp:sqlserver,1433;Database=phlosales;User Id=sa;Password=Pass@word;Integrated Security=false;TrustServerCertificate=true
        - BEARER_KEY=8833933cf99240db9389db678345b119
    ports:
      - 5002:80

  phlosales.web:
    image: ${DOCKER_REGISTRY-}phloweb
    build:
      context: .
      dockerfile: src/phlosales.web/Dockerfile
    ports:
      - 3000:3000

  phlosales.loadbalancer:
    image: ${DOCKER_REGISTRY-}phlolb
    build:
      context: .
      dockerfile: src/nginx/Dockerfile
    ports:
      - 5000:5000

volumes:
  sqldata:
