version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  phlosales.server:
    image: ${DOCKER_REGISTRY-}phlosalesserver
    build:
      context: .
      dockerfile: src/PhloSales.Server/Dockerfile
    ports:
      - 5000:80

volumes:
  sqldata: